export const INTEREST_RATE = 0.05;
export const NUMBER_OF_MONTHS_IN_YEAR = 12;
export const MIN_DEADLINE_YEARS = 4;
export const MAX_DEADLINE_YEARS = 30;
export const MIN_PAYMENT_DEADLINE = MIN_DEADLINE_YEARS * NUMBER_OF_MONTHS_IN_YEAR;
export const MAX_PAYMENT_DEADLINE = MAX_DEADLINE_YEARS * NUMBER_OF_MONTHS_IN_YEAR;
export const MIN_PERCENT = 10;
export const MAX_PERCENT = 100;
